set linesize 1000 ;



SELECT '{"target_id" : "' || TARGET_ID || '", "target_name" : "' || TARGET_NAME || '"},'
FROM OPB_TARG
WHERE (TARGET_ID,VERSION_NUMBER) IN (
    SELECT TARGET_ID,MAX(VERSION_NUMBER) VERSION_NUMBER FROM OPB_TARG GROUP BY TARGET_ID)
    AND SUBJ_ID = &1
ORDER BY TARGET_NAME;